### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by Sanceilaks** [QuiltMC/quilt-loader#467]
### Describe the crash

I'm not very familiar with how the loading works in quilt, but apparently the crash happens when quilt tries to read this file
```toml

[registry_sync]
	# Mod protocol is a feature allowing you to prevent clients with mismatched settings to join.
	# Client with mismatched values won't be able to connect to servers having this enabled.
	# It should be used only for non-vanilla compatible modpacks!
	# Protocol version. Needs to be the same on client and server. If it has value of -1, it won't be required by servers.
	# default: -1
	mod_protocol_version = -1
	# Protocol id. It should be different for every modpack, to prevent joining with mismatched mods.
	# default: my_quilt_modpack
	mod_protocol_id = "my_quilt_modpack"
	# A mod protocol name. Used for easier identification. Doesn't effect functionality
	# default: My Quilt Modpack
	mod_protocol_name = "My Quilt Modpack"
	# Message displayed for players joining with clients incompatible with Registry Sync. Supports strings and Minecraft's JSON text format.
	# default: {"translate":"qsl.registry_sync.unsupported_client","fallback":"Unsupported (vanilla?) client!\nThis server requires modded client to join!\n"}
	missing_registry_sync_message = "{\"translate\":\"qsl.registry_sync.unsupported_client\",\"fallback\":\"Unsupported (vanilla?) client!\\nThis server requires modded client to join!\\n\"}"
	# Top part of the message displayed for players joining with incompatible clients. Supports strings and Minecraft's JSON text format.
	# default: {"translate":"qsl.registry_sync.failed_sync","fallback":"Failed to synchronize client with the server!\nThis can happen when client's and server's mods don't match.\n"}
	mismatched_entries_top_message = "{\"translate\":\"qsl.registry_sync.failed_sync\",\"fallback\":\"Failed to synchronize client with the server!\\nThis can happen when client's and server's mods don't match.\\n\"}"
	# Bottom part of the message displayed for players joining with incompatible clients. Supports strings and Minecraft's JSON text format.
	# default: 
	mismatched_entries_bottom_message = ""
	# Shows some details about why client couldn't connect.
	# default: true
	mismatched_entries_show_details = true
	# Allows players with Fabric API to connect, as long as they have all required mods.
	# default: true
	support_fabric_api_protocol = true
	# Forces unknown clients to use the Fabric Registry Sync protocol fallback. Disables preventing Vanilla clients from joining.
	# default: false
	force_fabric_api_protocol_fallback = false
	# Disables the Mod Protocol sync on server list/initial query.
	# default: false
	disable_mod_protocol_ping = false
	# Disables the Registry Sync requirement. USE AT YOUR OWN RISK!
	# default: false
	disable_registry_sync = false
	# Disables validation of (block/fluid) states. USE AT YOUR OWN RISK!
	# default: false
	disable_state_validation = false
```

### Which environment crashed?

Client

### Logs

https://mclo.gs/oO4QEho
